using Discord;
using Discord.WebSocket;
using DiscordKeyBot.Infrastructure.Configuration;
using DiscordKeyBot.Models;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace DiscordKeyBot.Services;

public sealed class DiscordLogService : IDiscordLogService
{
    private readonly DiscordSocketClient _client;
    private readonly BotConfiguration _config;
    private readonly ILogger<DiscordLogService> _logger;

    public DiscordLogService(DiscordSocketClient client, IOptions<BotConfiguration> config, ILogger<DiscordLogService> logger)
    {
        _client = client;
        _config = config.Value;
        _logger = logger;
    }

    public Task LogKeyGeneratedAsync(string key, KeyType type, string generatedBy, DateTime expiration)
    {
        var embed = new EmbedBuilder()
            .WithTitle("🔑 Key Generated")
            .WithColor(Color.Green)
            .AddField("Key",          $"`{key}`",                           inline: false)
            .AddField("Type",         type.ToString(),                      inline: true)
            .AddField("Expires",      $"<t:{Unix(expiration)}:F>",         inline: true)
            .AddField("Generated By", generatedBy,                          inline: true)
            .WithFooter($"UTC: {DateTime.UtcNow:O}")
            .Build();

        return SendAsync(embed);
    }

    public Task LogKeyRedeemedAsync(string key, string discordUserId, DateTime expiration)
    {
        var embed = new EmbedBuilder()
            .WithTitle("✅ Key Redeemed")
            .WithColor(Color.Blue)
            .AddField("Key",     $"`{key}`",                             inline: false)
            .AddField("User",    $"<@{discordUserId}> ({discordUserId})", inline: true)
            .AddField("Expires", $"<t:{Unix(expiration)}:F>",            inline: true)
            .WithFooter($"UTC: {DateTime.UtcNow:O}")
            .Build();

        return SendAsync(embed);
    }

    public Task LogKeyRevokedAsync(string key, string revokedBy)
    {
        var embed = new EmbedBuilder()
            .WithTitle("🚫 Key Revoked")
            .WithColor(Color.Red)
            .AddField("Key",        $"`{key}`", inline: false)
            .AddField("Revoked By", revokedBy,  inline: true)
            .WithFooter($"UTC: {DateTime.UtcNow:O}")
            .Build();

        return SendAsync(embed);
    }

    public Task LogInfoAsync(string title, string message) =>
        SendAsync(new EmbedBuilder()
            .WithTitle($"ℹ️ {title}")
            .WithDescription(message)
            .WithColor(Color.LightGrey)
            .Build());

    public Task LogErrorAsync(string title, string message) =>
        SendAsync(new EmbedBuilder()
            .WithTitle($"⚠️ {title}")
            .WithDescription(message)
            .WithColor(Color.Orange)
            .Build());

    private async Task SendAsync(Embed embed)
    {
        if (_config.LogChannelId == 0)
        {
            _logger.LogWarning("LOG_CHANNEL_ID is not set, skipping log embed.");
            return;
        }

        try
        {
            if (_client.GetChannel(_config.LogChannelId) is not IMessageChannel channel)
            {
                _logger.LogWarning("Log channel {Id} not found.", _config.LogChannelId);
                return;
            }

            await channel.SendMessageAsync(embed: embed);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to send log embed to channel {Id}", _config.LogChannelId);
        }
    }

    private static long Unix(DateTime utc) => new DateTimeOffset(utc, TimeSpan.Zero).ToUnixTimeSeconds();
}
